import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const config = window.AUTOVALUE_CONFIG || {};
const STORAGE_KEY = 'autovalue-pro-v1';
const PHOTO_BUCKET = config.photoBucket || 'vehicle-photos';
      const EQUIPMENT = ['Klima','Klimaautomatik','3-Zonen-Klima','Navi','Apple CarPlay','Android Auto','Wireless CarPlay','LED','Xenon','Matrix','Fernlichtassistent','Tempomat','ACC','Abstandswarner','Lane Assist','Spurhalteassistent','Totwinkel','Verkehrszeichenerkennung','Müdigkeitswarner','Rückfahrkamera','360° Kamera','PDC vorne','PDC hinten','Parkassistent','Sitzheizung','Lenkradheizung','Sitzbelüftung','Memory-Sitze','Panorama','Leder','Alcantara','Sportsitze','Schiebedach','AHK','Bluetooth','DAB+','Head-up-Display','Schaltwippen','Keyless','Start-Stopp','Winterpaket','Lichtpaket','Soundsystem','Digitales Cockpit','Ambientebeleuchtung','Elektrische Heckklappe','Elektrische Sitze','Isofix','Notbremsassistent','Regensensor','Leichtmetallfelgen','Sommerreifen','Winterreifen','Allwetterreifen','Standheizung','Wärmepumpe','Luftfederung','Allrad','Ladekabel'];
      const MONEY_FIELDS = ['purchasePrice','transportCost','registrationCost','repairCost','cleaningCost','listingCost','otherCost','desiredSalePrice','soldPrice','taxes'];
      const initialVehicles = [
        {id:'demo-1',brand:'Ford',model:'Fiesta',series:'MK7',generation:'7',body:'Kleinwagen',year:2014,mileage:120000,ps:85,gearbox:'Handschaltung',fuel:'Benzin',askingPrice:4950,purchasePrice:4200,transportCost:180,registrationCost:110,repairCost:240,cleaningCost:75,listingCost:40,desiredSalePrice:6300,soldPrice:0,taxes:165,status:'In Aufbereitung',equipment:['Klima','Bluetooth','PDC hinten'],notes:'Stoßdämpfer vorne prüfen.',favourite:true,location:'Bremen',updatedAt:'2026-08-17T09:15:00',createdBy:'Daniel'},
        {id:'demo-2',brand:'Volkswagen',model:'Golf',series:'Golf 7',generation:'7',body:'Limousine',year:2015,mileage:148000,ps:125,gearbox:'DSG',fuel:'Benzin',askingPrice:7900,purchasePrice:7000,transportCost:0,registrationCost:120,repairCost:310,cleaningCost:95,listingCost:55,desiredSalePrice:9400,soldPrice:0,taxes:260,status:'Inseriert',equipment:['Klimaautomatik','Navi','Tempomat','Sitzheizung','PDC hinten'],notes:'Gepflegter Innenraum.',favourite:false,location:'Hamburg',updatedAt:'2026-08-16T14:25:00',createdBy:'Ben'},
        {id:'demo-3',brand:'Ford',model:'Fiesta',series:'MK7',generation:'7',body:'Kleinwagen',year:2013,mileage:132000,ps:82,gearbox:'Handschaltung',fuel:'Benzin',askingPrice:4100,purchasePrice:3450,transportCost:140,registrationCost:105,repairCost:180,cleaningCost:60,listingCost:40,desiredSalePrice:5350,soldPrice:5350,taxes:180,status:'Verkauft',equipment:['Klima','Bluetooth'],notes:'Schnell verkauft.',favourite:false,location:'Oldenburg',updatedAt:'2026-08-13T18:40:00',createdBy:'Daniel'},
        {id:'demo-4',brand:'Audi',model:'A3',series:'8V',generation:'8V',body:'Sportback',year:2014,mileage:169000,ps:150,gearbox:'Automatik',fuel:'Diesel',askingPrice:9950,purchasePrice:8600,transportCost:200,registrationCost:120,repairCost:480,cleaningCost:130,listingCost:60,desiredSalePrice:11700,soldPrice:0,taxes:340,status:'Besichtigung geplant',equipment:['Klimaautomatik','Navi','LED','Tempomat','PDC hinten'],notes:'Probefahrt am Mittwoch.',favourite:true,location:'Hannover',updatedAt:'2026-08-17T07:30:00',createdBy:'Ben'}
      ];
      const defaultState = { version:1, vehicles:[], tasks:[], updatedAt:new Date().toISOString(), lastModifiedBy:null };
      const client = config.supabaseUrl && config.supabasePublishableKey ? createClient(config.supabaseUrl, config.supabasePublishableKey) : null;
      const photoUrls = new Map();
      let state = loadState(); let currentView = 'home'; let editPhoto = ''; let editImportMeta = null; let currentUser = null; let workspaceId = null; let realtimeChannel = null; let saveChain = Promise.resolve(); let currentDetailId = null;
      const $ = sel => document.querySelector(sel); const $$ = sel => [...document.querySelectorAll(sel)];
      const euro = value => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(value || 0));
      const num = value => Number(value || 0);
      const formatDate = value => value ? new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(value)) : '–';
      const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
      function loadState(){ try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY)); return stored && Array.isArray(stored.vehicles) && Array.isArray(stored.tasks) ? stored : structuredClone(defaultState); } catch { return structuredClone(defaultState); } }
      function normaliseState(value){ return value && Array.isArray(value.vehicles) && Array.isArray(value.tasks) ? value : structuredClone(defaultState); }
      function visibleVehicles(){ return (state.vehicles || []).filter(vehicle => !vehicle.deletedAt); }
      function setSyncStatus(status, label){ const dot=$('#sync-dot'), text=$('#sync-label'); if(!dot || !text) return; dot.className=`sync-dot ${status||''}`; text.textContent=label; }
      function cacheState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
      function saveState(){ cacheState(); if(!client || !workspaceId) return Promise.resolve(); const snapshot=structuredClone(state); saveChain=saveChain.then(async()=>{try{setSyncStatus('', 'Speichere …'); const {data,error}=await client.rpc('av_save_workspace_state',{p_state:snapshot}); if(error) throw error; state=normaliseState(data); cacheState(); setSyncStatus('online','Synchronisiert'); refreshActiveView(); hydratePhotoUrls();}catch(error){setSyncStatus('error','Nicht synchronisiert');notice(error.message||'Speichern fehlgeschlagen.');}}); return saveChain; }
      function refreshActiveView(){ if(currentView==='home')renderHome(); else if(currentView==='autos')renderVehicles(); else if(currentView==='search')renderSearch(); else if(currentView==='statistics')renderStatistics(); else if(currentView==='favorites')renderFavorites(); else if(currentView==='profile')$('#name-setting').value=currentUser?.name||''; else if(currentView==='detail'&&currentDetailId)detailView(currentDetailId); }
      function startRealtime(){ if(realtimeChannel) client.removeChannel(realtimeChannel); if(!client||!workspaceId)return; realtimeChannel=client.channel(`av-workspace-${workspaceId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'av_workspaces',filter:`id=eq.${workspaceId}`},payload=>{try{const incoming=normaliseState(payload.new.state);const changedByOther=incoming.lastModifiedBy&&incoming.lastModifiedBy!==currentUser?.name&&incoming.version!==state.version;state=incoming;cacheState();setSyncStatus('online','Synchronisiert');refreshActiveView();hydratePhotoUrls();if(changedByOther)notice(`${incoming.lastModifiedBy} hat den Bestand aktualisiert.`);}catch{}}).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setSyncStatus('error','Verbindung wird erneuert …');}); }
      function vehicleProfit(v){ const costs = ['purchasePrice','transportCost','registrationCost','repairCost','cleaningCost','listingCost','otherCost'].reduce((sum,key)=>sum+num(v[key]),0); const sale = num(v.soldPrice) || num(v.desiredSalePrice); return { costs, sale, gross:sale-costs, net:sale-costs-num(v.taxes), margin: costs ? ((sale-costs-num(v.taxes))/costs)*100 : 0 }; }
      function similarVehicles(v){ return visibleVehicles().filter(other => other.id !== v.id && other.brand?.toLowerCase() === v.brand?.toLowerCase() && other.model?.toLowerCase() === v.model?.toLowerCase()); }
      function vehicleScore(v){ const peers = similarVehicles(v); const reference = peers.length ? peers.reduce((a,b)=>a+(num(b.askingPrice)||num(b.desiredSalePrice)),0)/peers.length : num(v.askingPrice)||num(v.desiredSalePrice); const price = num(v.purchasePrice)||num(v.askingPrice); const pricePoints = reference && price ? Math.max(0,Math.min(35,18+((reference-price)/reference)*100)) : 18; const mileagePoints = num(v.mileage) ? Math.max(0,Math.min(18,18-(num(v.mileage)/25000))) : 8; const age = new Date().getFullYear()-num(v.year); const agePoints = v.year ? Math.max(3,Math.min(14,14-age*.45)) : 7; const equipmentPoints = Math.min(15,(v.equipment?.length || 0)*1.8); const profit = vehicleProfit(v).net; const profitPoints = Math.max(0,Math.min(18,8+profit/100)); return Math.round(Math.max(0,Math.min(100,pricePoints+mileagePoints+agePoints+equipmentPoints+profitPoints))); }
      function scoreClass(score){ return score >= 70 ? 'good' : score >= 45 ? 'mid' : 'bad'; }
      function scoreLabel(score){ return score >= 70 ? 'Sehr guter Preis' : score >= 45 ? 'Normaler Preis' : 'Zu teuer'; }
      function displayPhoto(photo){ return typeof photo==='string' && photo.startsWith('storage://') ? (photoUrls.get(photo)||'') : photo; }
      async function cachePhotoUrl(photo){ if(!photo||!photo.startsWith('storage://')||photoUrls.has(photo)||!client)return; const {data,error}=await client.storage.from(PHOTO_BUCKET).createSignedUrl(photo.slice('storage://'.length),604800); if(!error&&data?.signedUrl)photoUrls.set(photo,data.signedUrl); }
      async function hydratePhotoUrls(){ const photos=[...new Set((state.vehicles||[]).map(vehicle=>vehicle.photo).filter(photo=>typeof photo==='string'&&photo.startsWith('storage://')))]; if(!photos.length)return; await Promise.all(photos.map(cachePhotoUrl)); refreshActiveView(); }
      function thumbnail(v, className='vehicle-thumb'){ const photo=displayPhoto(v.photo); return `<div class="${className}">${photo ? `<img src="${photo}" alt="${esc(v.brand)} ${esc(v.model)}" />` : '🚘'}</div>`; }
      function notice(text){ const n=$('#notice'); n.textContent=text; n.classList.add('show'); setTimeout(()=>n.classList.remove('show'),2600); }
      function updateOperations(mutator){ mutator(state); state.version=num(state.version)+1; state.updatedAt=new Date().toISOString(); state.lastModifiedBy=currentUser?.name||state.name||'CarsAutoHaus'; cacheState(); saveState(); document.dispatchEvent(new CustomEvent('carsautohaus:operations-updated')); }
      window.CarsAutoHaus = { getState:()=>structuredClone(state), update:updateOperations, go:showView, notify:notice, euro, formatDate, vehicles:()=>structuredClone(visibleVehicles()) };
      document.dispatchEvent(new CustomEvent('carsautohaus:ready'));
function showView(view){ currentView=view; document.dispatchEvent(new CustomEvent('autovalue:view-changed',{detail:{view}})); $$('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}-view`)); $$('.nav-button').forEach(el=>el.classList.toggle('active',el.dataset.go===view)); const mobileSave=$('#mobile-form-save'), mobileNew=$('#mobile-new'); if(mobileSave) mobileSave.hidden=view!=='form'; if(mobileNew) mobileNew.hidden=view==='form'; if(view==='home') renderHome(); if(view==='autos') renderVehicles(); if(view==='search') renderSearch(); if(view==='statistics') renderStatistics(); if(view==='favorites') renderFavorites(); if(view==='profile') $('#name-setting').value=currentUser?.name||''; window.scrollTo({top:0,behavior:'smooth'}); }
      function renderHome(){ const vehicles=visibleVehicles(); $('#user-name').textContent=currentUser?.name||state.name; $('#today').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long'}).format(new Date()); const sold=vehicles.filter(v=>v.status==='Verkauft'); const active=vehicles.filter(v=>!['Verkauft','Archiviert'].includes(v.status)); const avg=sold.length ? sold.reduce((sum,v)=>sum+vehicleProfit(v).net,0)/sold.length : vehicles.length ? vehicles.reduce((sum,v)=>sum+vehicleProfit(v).net,0)/vehicles.length : 0; const todayCount=vehicles.filter(v=>new Date(v.updatedAt||0).toDateString()===new Date().toDateString()).length; $('#stats-grid').innerHTML = [['Neue Autos',todayCount,''],['Insgesamt gespeichert',vehicles.length,''],['Durchschn. Gewinn',euro(avg),avg>=0?'up':''],['Offene Fahrzeuge',active.length,''],['Bereits verkauft',sold.length,'']].map(([l,v,c])=>`<article class="card stat"><span>${l}</span><strong class="${c}">${v}</strong></article>`).join(''); const recent=[...vehicles].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,4); $('#recent-list').innerHTML=recent.length?recent.map(rowHtml).join(''):`<div class="empty"><span class="empty-icon">🚗</span>Noch keine Fahrzeuge gespeichert.</div>`; renderTasks(); }
      function rowHtml(v){ const p=vehicleProfit(v); const s=vehicleScore(v); return `<div class="vehicle-row" data-detail="${v.id}">${thumbnail(v)}<div><div class="vehicle-name">${esc(v.brand)} ${esc(v.model)}</div><div class="vehicle-meta">${esc(v.year)} · ${num(v.mileage).toLocaleString('de-DE')} km · ${esc(v.status)}</div></div><div class="row-value"><span class="score ${scoreClass(s)}">${s}</span><div class="${p.net>=0?'profit-positive':'profit-negative'}" style="margin-top:5px">${euro(p.net)}</div></div></div>`; }
      function renderTasks(){ const taskList=$('#task-list'); taskList.innerHTML=state.tasks.length?state.tasks.sort((a,b)=>a.date.localeCompare(b.date)).map(t=>`<label class="task"><input class="task-check" type="checkbox" data-task="${t.id}" ${t.done?'checked':''}/><span>${esc(t.title)}<time>${formatDate(t.date)}</time></span></label>`).join(''):`<div class="empty">Keine offenen Aufgaben.</div>`; }
      function vehicleCard(v){ const p=vehicleProfit(v), s=vehicleScore(v), photo=displayPhoto(v.photo); return `<article class="card vehicle-card" data-detail="${v.id}"><div class="vehicle-cover">${photo?`<img src="${photo}" alt="${esc(v.brand)} ${esc(v.model)}" />`:'🚘'}<button class="favourite" data-favorite="${v.id}" title="Favorit">${v.favourite?'★':'☆'}</button></div><div class="vehicle-body"><div class="vehicle-title"><b>${esc(v.brand)} ${esc(v.model)}</b><span class="score ${scoreClass(s)}">${s}</span></div><div class="vehicle-price">${euro(num(v.askingPrice)||num(v.purchasePrice))}</div><div class="vehicle-detail">${esc(v.year)} · ${num(v.mileage).toLocaleString('de-DE')} km · ${esc(v.gearbox||'–')}</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:12px"><span class="pill">${esc(v.status)}</span><b class="${p.net>=0?'profit-positive':'profit-negative'}">${euro(p.net)}</b></div></div></article>`; }
      function renderVehicles(){ let vehicles=[...visibleVehicles()]; const query=$('#vehicle-search').value.trim().toLowerCase(); const status=$('#status-filter').value; const sort=$('#sort-filter').value; if(query) vehicles=vehicles.filter(v=>[v.brand,v.model,v.series,v.generation,v.engineCode,v.fuel].join(' ').toLowerCase().includes(query)); if(status) vehicles=vehicles.filter(v=>v.status===status); vehicles.sort((a,b)=>sort==='score'?vehicleScore(b)-vehicleScore(a):sort==='profit'?vehicleProfit(b).net-vehicleProfit(a).net:sort==='price'?(num(a.askingPrice)||num(a.purchasePrice))-(num(b.askingPrice)||num(b.purchasePrice)):new Date(b.updatedAt)-new Date(a.updatedAt)); $('#vehicle-grid').innerHTML=vehicles.length?vehicles.map(vehicleCard).join(''):`<div class="empty card" style="grid-column:1/-1"><span class="empty-icon">🔎</span>Keine passenden Fahrzeuge gefunden.</div>`; }
      function renderFavorites(){ const vehicles=visibleVehicles().filter(v=>v.favourite); $('#favorite-grid').innerHTML=vehicles.length?vehicles.map(vehicleCard).join(''):`<div class="empty card" style="grid-column:1/-1"><span class="empty-icon">☆</span>Du hast noch keine Fahrzeuge als Favorit markiert.</div>`; }
      function readCompareFilters(){ return {brand:$('#compare-brand').value.trim().toLowerCase(),model:$('#compare-model').value.trim().toLowerCase(),year:num($('#compare-year').value),mileage:num($('#compare-km').value),price:num($('#compare-price').value),gearbox:$('#compare-gear').value}; }
      function filterComparisons(){ const f=readCompareFilters(); return visibleVehicles().filter(v=>(!f.brand||v.brand?.toLowerCase().includes(f.brand))&&(!f.model||v.model?.toLowerCase().includes(f.model))&&(!f.year||num(v.year)>=f.year)&&(!f.mileage||num(v.mileage)<=f.mileage)&&(!f.price||(num(v.askingPrice)||num(v.purchasePrice))<=f.price)&&(!f.gearbox||v.gearbox===f.gearbox)); }
      function renderSearch(){ const vehicles=filterComparisons(); const prices=vehicles.map(v=>num(v.askingPrice)||num(v.purchasePrice)).filter(Boolean).sort((a,b)=>a-b); const avg=prices.length?prices.reduce((a,b)=>a+b,0)/prices.length:0; const median=prices.length?prices[Math.floor(prices.length/2)]:0; $('#comparison-summary').innerHTML=vehicles.length?`<div class="metrics"><article class="card metric"><span>Passende Fahrzeuge</span><b>${vehicles.length}</b></article><article class="card metric"><span>Durchschnittspreis</span><b>${euro(avg)}</b></article><article class="card metric"><span>Median</span><b>${euro(median)}</b></article><article class="card metric"><span>Preisspanne</span><b>${euro(prices[0])} – ${euro(prices.at(-1))}</b></article></div>`:`<div class="empty card">Starte eine Suche oder passe die Filter an.</div>`; $('#comparison-results').innerHTML=vehicles.length?vehicles.sort((a,b)=>vehicleScore(b)-vehicleScore(a)).map(v=>{const p=vehicleProfit(v),s=vehicleScore(v);return `<article class="compare-item" data-detail="${v.id}"><div><b>${esc(v.brand)} ${esc(v.model)} · ${esc(v.year)}</b><div class="vehicle-meta">${num(v.mileage).toLocaleString('de-DE')} km · ${esc(v.gearbox||'–')} · ${esc(v.status)}</div></div><b>${euro(num(v.askingPrice)||num(v.purchasePrice))}</b><span class="score ${scoreClass(s)}">${s} · ${scoreLabel(s)}</span></article>`}).join(''):''; }
      function renderStatistics(){ const vehicles=visibleVehicles(); const sold=vehicles.filter(v=>v.status==='Verkauft'); const total=sold.reduce((s,v)=>s+vehicleProfit(v).net,0); const avg=sold.length?total/sold.length:0; const brands={}; const models={}; const statuses={}; vehicles.forEach(v=>{const p=vehicleProfit(v).net; brands[v.brand]=(brands[v.brand]||{profit:0,count:0});brands[v.brand].profit+=p;brands[v.brand].count++;const m=`${v.brand} ${v.model}`;models[m]=(models[m]||0)+p;statuses[v.status]=(statuses[v.status]||0)+1;}); const bestBrand=Object.entries(brands).sort((a,b)=>b[1].profit-a[1].profit)[0]; const purchaseAvg=vehicles.length?vehicles.reduce((s,v)=>s+num(v.purchasePrice),0)/vehicles.length:0; const saleAvg=sold.length?sold.reduce((s,v)=>s+num(v.soldPrice),0)/sold.length:0; $('#metrics').innerHTML=[['Gesamtgewinn',euro(total)],['Monatsgewinn',euro(total)],['Durchschn. Gewinn',euro(avg)],['Beste Marke',bestBrand?bestBrand[0]:'–'],['Ø Einkauf',euro(purchaseAvg)],['Ø Verkauf',euro(saleAvg)]].map(x=>`<article class="card metric"><span>${x[0]}</span><b class="${x[0].includes('Gewinn')&&total<0?'profit-negative':''}">${x[1]}</b></article>`).join(''); const graph=[...vehicles].sort((a,b)=>new Date(a.updatedAt)-new Date(b.updatedAt)).slice(-9); const maximum=Math.max(1,...graph.map(v=>Math.abs(vehicleProfit(v).net))); $('#profit-chart').innerHTML=graph.length?graph.map(v=>{const p=vehicleProfit(v).net;return `<div class="bar" title="${esc(v.brand)} ${esc(v.model)}: ${euro(p)}" style="height:${Math.max(8,Math.abs(p)/maximum*100)}%;background:${p>=0?'linear-gradient(180deg,#3b9bff,#1658bf)':'linear-gradient(180deg,#ed7d89,#a63545)'}"><span>${esc(v.model)}</span></div>`}).join(''):`<p class="muted">Noch keine Daten vorhanden.</p>`; $('#top-models').innerHTML=Object.entries(models).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,profit])=>`<div class="vehicle-row"><div class="vehicle-thumb">🏆</div><div><div class="vehicle-name">${esc(name)}</div><div class="vehicle-meta">Gesamtergebnis</div></div><b class="${profit>=0?'profit-positive':'profit-negative'}">${euro(profit)}</b></div>`).join('')||'<p class="muted">Noch keine Fahrzeuge vorhanden.</p>'; $('#status-distribution').innerHTML=Object.entries(statuses).sort((a,b)=>b[1]-a[1]).map(([status,count])=>`<div class="vehicle-row"><div class="vehicle-thumb">${status==='Verkauft'?'✓':'🚗'}</div><div><div class="vehicle-name">${esc(status)}</div><div class="vehicle-meta">${count} Fahrzeug${count!==1?'e':''}</div></div><b>${count}</b></div>`).join('')||'<p class="muted">Noch keine Fahrzeuge vorhanden.</p>'; }
      function renderEquipment(){ const selected=new Set([...$$('#equipment-checkboxes input:checked')].map(input=>input.value)); const query=$('#equipment-search')?.value.trim().toLowerCase()||''; const matches=EQUIPMENT.filter(item=>!query||item.toLowerCase().includes(query)); $('#equipment-checkboxes').innerHTML=matches.length?matches.map(item=>`<label class="check-label"><input type="checkbox" name="equipment" value="${esc(item)}" ${selected.has(item)?'checked':''} /> ${esc(item)}</label>`).join(''):'<span class="muted">Keine passende Ausstattung gefunden.</span>'; }
      function renderCostSummary(){ const form=$('#vehicle-form'); const vals=Object.fromEntries(new FormData(form)); const v=Object.fromEntries(MONEY_FIELDS.map(k=>[k,num(vals[k])])); const result=vehicleProfit(v); $('#cost-summary').innerHTML=`<div><span>Gesamtkosten</span><b>${euro(result.costs)}</b></div><div><span>Verkaufsprognose</span><b>${euro(result.sale)}</b></div><div><span>Bruttogewinn</span><b class="${result.gross>=0?'profit-positive':'profit-negative'}">${euro(result.gross)}</b></div><div><span>Nettogewinn · Marge</span><b class="${result.net>=0?'profit-positive':'profit-negative'}">${euro(result.net)} · ${result.margin.toFixed(1).replace('.',',')} %</b></div>`; }
      function setPhotoPreview(photo){ const display=displayPhoto(photo); $('#photo-preview').innerHTML=display?`<img src="${display}" alt="Vorschau" />`:'🚘'; if(photo&&photo.startsWith('storage://')&&!display)cachePhotoUrl(photo).then(()=>{if(editPhoto===photo)setPhotoPreview(photo);}); }
      function newVehicleId(){ return `car-${crypto.randomUUID ? crypto.randomUUID() : Date.now()}`; }
function fillForm(v){ const form=$('#vehicle-form'); form.reset(); $('#vehicle-id').value=v?.id||newVehicleId(); $('#form-heading').textContent=v?'Fahrzeug bearbeiten':'Neues Auto hinzufügen'; editPhoto=v?.photo||''; editImportMeta=v?.importedAt?{importedAt:v.importedAt}:null; for(const [key,val] of Object.entries(v||{})){ const field=form.elements[key]; if(!field) continue; if(field.type==='checkbox') field.checked=Boolean(val); else field.value=val ?? ''; } $$('#equipment-checkboxes input').forEach(x=>x.checked=(v?.equipment||[]).includes(x.value)); $('#photo-data').value=editPhoto; setPhotoPreview(editPhoto); renderCostSummary(); document.dispatchEvent(new CustomEvent('autovalue:form-filled')); }
      function collectForm(){ const form=$('#vehicle-form'); const fd=new FormData(form); const vehicle=Object.fromEntries(fd.entries()); vehicle.id=vehicle.id||`car-${Date.now()}`; ['year','mileage','ps','kw','displacement','owners','co2','consumption','keyCount','askingPrice','purchasePrice','targetPrice','transportCost','registrationCost','repairCost','cleaningCost','listingCost','otherCost','desiredSalePrice','soldPrice','taxes','rating'].forEach(k=>vehicle[k]=num(vehicle[k])); ['accidentFree','serviceBook','garage','nonSmoker','imported','towbar'].forEach(k=>vehicle[k]=form.elements[k].checked); vehicle.equipment=[...form.querySelectorAll('input[name="equipment"]:checked')].map(el=>el.value); vehicle.photo=editPhoto; Object.assign(vehicle,editImportMeta||{}); vehicle.updatedAt=new Date().toISOString(); vehicle.createdBy=currentUser?.name||state.name; return vehicle; }
      function detailView(id){ const v=visibleVehicles().find(x=>x.id===id); if(!v)return; currentDetailId=id; const p=vehicleProfit(v),s=vehicleScore(v), peers=similarVehicles(v); const median=peers.length?[...peers].map(x=>num(x.askingPrice)||num(x.desiredSalePrice)).sort((a,b)=>a-b)[Math.floor(peers.length/2)]:0; const details=[['Baujahr',v.year],['Kilometer',`${num(v.mileage).toLocaleString('de-DE')} km`],['Leistung',v.ps?`${v.ps} PS`:'–'],['Getriebe',v.gearbox||'–'],['Gesamtkosten',euro(p.costs)],['Verkaufsprognose',euro(p.sale)],['Nettogewinn',euro(p.net)],['Ausstattung',`${v.equipment?.length||0} Extras`]]; $('#detail-content').innerHTML=`<div class="hero"><div class="details-title">${thumbnail(v,'detail-cover')}<div><h1>${esc(v.brand)} ${esc(v.model)}</h1><p class="subtitle">${esc(v.series||v.generation||'Fahrzeugakte')} · ${esc(v.status)}</p><span class="score ${scoreClass(s)}">${s}/100 · ${scoreLabel(s)}</span></div></div><div class="actions"><button class="secondary" data-edit="${v.id}">Bearbeiten</button><button class="icon-button" data-delete="${v.id}" title="Fahrzeug löschen">⌫</button></div></div><div class="detail-grid">${details.map(([k,val])=>`<article class="card detail-item"><span>${k}</span><b class="${k==='Nettogewinn'?(p.net>=0?'profit-positive':'profit-negative'):''}">${esc(val)}</b></article>`).join('')}</div><div class="section split"><article class="card list-card"><div class="compare-header"><div><h2>Preisvergleich</h2><p class="muted">${peers.length?`${peers.length} ähnliche Fahrzeuge in deiner Datenbank.`:'Noch keine ähnlichen Fahrzeuge gespeichert.'}</p></div><button class="secondary" data-go="search">Suche öffnen</button></div>${peers.length?`<div class="metrics"><article class="card metric"><span>Medianpreis</span><b>${euro(median)}</b></article><article class="card metric"><span>Preisposition</span><b>${num(v.askingPrice||v.purchasePrice)<=median?'🟢 Günstig':'🔴 Hoch'}</b></article></div><div class="compare-list" style="margin-top:14px">${peers.slice(0,4).map(x=>`<div class="compare-item"><div><b>${esc(x.brand)} ${esc(x.model)} · ${esc(x.year)}</b><div class="vehicle-meta">${num(x.mileage).toLocaleString('de-DE')} km</div></div><b>${euro(x.askingPrice||x.purchasePrice)}</b><button class="secondary" data-compare="${v.id}|${x.id}">Vergleichen</button></div>`).join('')}</div>`:'<div class="empty">Füge ähnliche Fahrzeuge hinzu, damit die Preisbewertung noch genauer wird.</div>'}</article><article class="card list-card"><h2>Notizen</h2><p class="muted">${esc(v.notes||'Keine Notizen vorhanden.')}</p><h3 style="margin-top:20px">Ausstattung</h3><div style="display:flex;gap:6px;flex-wrap:wrap">${(v.equipment||[]).map(e=>`<span class="pill">${esc(e)}</span>`).join('')||'<span class="muted">Keine Ausstattung erfasst.</span>'}</div></article></div><div class="section"><button class="secondary" data-go="autos">← Zurück zu allen Fahrzeugen</button></div>`; showView('detail'); }
      function compareVehicles(idA,idB){ const a=visibleVehicles().find(v=>v.id===idA), b=visibleVehicles().find(v=>v.id===idB); if(!a||!b)return; const pA=vehicleProfit(a),pB=vehicleProfit(b); const rows=[['Preis',num(a.askingPrice)||num(a.purchasePrice),num(b.askingPrice)||num(b.purchasePrice),'money'],['Kilometer',num(a.mileage),num(b.mileage),'number'],['Baujahr',num(a.year),num(b.year),'number'],['PS',num(a.ps),num(b.ps),'number'],['Getriebe',a.gearbox||'–',b.gearbox||'–','text'],['Ausstattung',(a.equipment||[]).length,(b.equipment||[]).length,'number'],['Nettogewinn',pA.net,pB.net,'money']]; const pretty=(x,t)=>t==='money'?euro(x):t==='number'?Number(x).toLocaleString('de-DE'):esc(x); $('#compare-modal-content').innerHTML=`<table class="comparison-table"><thead><tr><th>Merkmal</th><th>${esc(a.brand)} ${esc(a.model)}</th><th>${esc(b.brand)} ${esc(b.model)}</th></tr></thead><tbody>${rows.map(([key,left,right,type])=>{let l='',r='';if(type==='money'){l=left<right?'profit-positive':left>right?'profit-negative':'';r=right<left?'profit-positive':right>left?'profit-negative':'';}else if(key==='Kilometer'){l=left<right?'profit-positive':left>right?'profit-negative':'';r=right<left?'profit-positive':right>left?'profit-negative':'';}else if(['Baujahr','PS','Ausstattung'].includes(key)){l=left>right?'profit-positive':left<right?'profit-negative':'';r=right>left?'profit-positive':right<left?'profit-negative':'';}return `<tr><th>${key}</th><td class="${l}">${pretty(left,type)}</td><td class="${r}">${pretty(right,type)}</td></tr>`}).join('')}</tbody></table>`; $('#compare-modal').classList.add('open'); }
      function exportCsv(){ const heads=['Marke','Modell','Baujahr','Kilometer','Einkaufspreis','Gesamtkosten','Verkaufspreis','Nettogewinn','Marge %','Status','Score']; const lines=visibleVehicles().map(v=>{const p=vehicleProfit(v);return [v.brand,v.model,v.year,v.mileage,v.purchasePrice,p.costs,p.sale,p.net,p.margin.toFixed(2),v.status,vehicleScore(v)].map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(';')}); const blob=new Blob([[heads.join(';'),...lines].join('\n')],{type:'text/csv;charset=utf-8;'}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=`carsautohaus-export-${new Date().toISOString().slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(link.href); notice('CSV-Export wurde erstellt.'); }
      renderEquipment(); $('#equipment-search')?.addEventListener('input',renderEquipment); $('#equipment-search-clear')?.addEventListener('click',()=>{$('#equipment-search').value='';renderEquipment();$('#equipment-search').focus();});
      document.addEventListener('click',event=>{const go=event.target.closest('[data-go]'); if(go){if(go.dataset.go==='form')fillForm();showView(go.dataset.go);return;} const detail=event.target.closest('[data-detail]'); if(detail&&!event.target.closest('[data-favorite]')){detailView(detail.dataset.detail);return;} const favorite=event.target.closest('[data-favorite]'); if(favorite){const v=state.vehicles.find(x=>x.id===favorite.dataset.favorite);v.favourite=!v.favourite;v.updatedAt=new Date().toISOString();saveState();renderVehicles();renderFavorites();renderHome();return;} const edit=event.target.closest('[data-edit]');if(edit){fillForm(state.vehicles.find(v=>v.id===edit.dataset.edit));showView('form');return;}const del=event.target.closest('[data-delete]');if(del){const v=state.vehicles.find(x=>x.id===del.dataset.delete);if(confirm(`${v.brand} ${v.model} wirklich löschen?`)){v.deletedAt=new Date().toISOString();v.updatedAt=v.deletedAt;saveState();notice('Fahrzeug gelöscht.');showView('autos');}return;} const cmp=event.target.closest('[data-compare]');if(cmp){compareVehicles(...cmp.dataset.compare.split('|'));return;} if(event.target.matches('[data-close-modal]')||event.target.classList.contains('modal-backdrop')) event.target.closest('.modal-backdrop')?.classList.remove('open'); });
      $('#home-button').addEventListener('click',()=>showView('home')); $('#settings-button').addEventListener('click',()=>showView('profile')); $('#vehicle-search').addEventListener('input',renderVehicles); $('#status-filter').addEventListener('change',renderVehicles); $('#sort-filter').addEventListener('change',renderVehicles); $('#run-compare').addEventListener('click',renderSearch); $('#export-button').addEventListener('click',exportCsv); $('#profile-export').addEventListener('click',exportCsv);
      $('#backup-import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const incoming=normaliseState(parsed.state||parsed);if(!Array.isArray(incoming.vehicles)||!Array.isArray(incoming.tasks))throw new Error('Die Datei enthält keinen gültigen CarsAutoHaus-Datenbestand.');if(!confirm(`${incoming.vehicles.length} Fahrzeuge und ${incoming.tasks.length} Aufgaben in den gemeinsamen Bestand übernehmen?`))return;state=incoming;cacheState();await saveState();notice('Sicherung wurde in den gemeinsamen Bestand übernommen.');}catch(problem){notice(problem.message||'Die Sicherung konnte nicht gelesen werden.');}finally{event.target.value='';}});
      $('#vehicle-form').addEventListener('input',event=>{if(event.target.matches('.money-input'))renderCostSummary();}); $('#vehicle-form').addEventListener('submit',event=>{event.preventDefault(); const vehicle=collectForm(); const oldIndex=state.vehicles.findIndex(v=>v.id===vehicle.id); if(oldIndex>-1)state.vehicles[oldIndex]={...state.vehicles[oldIndex],...vehicle};else state.vehicles.unshift(vehicle);saveState();notice(oldIndex>-1?'Fahrzeug aktualisiert.':'Fahrzeug gespeichert und bewertet.');detailView(vehicle.id);});
      $('#photo-input').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(!client||!workspaceId){notice('Bitte zuerst anmelden.');return;}if(!file.type.startsWith('image/')||file.size>3*1024*1024){notice('Bitte ein Bild unter 3 MB auswählen.');event.target.value='';return;}try{setSyncStatus('','Foto wird hochgeladen …');const vehicleId=$('#vehicle-id').value||newVehicleId();$('#vehicle-id').value=vehicleId;const extension=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').slice(0,8)||'jpg';const objectPath=`${workspaceId}/${vehicleId}/${crypto.randomUUID ? crypto.randomUUID() : Date.now()}.${extension}`;const {error}=await client.storage.from(PHOTO_BUCKET).upload(objectPath,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(error)throw error;editPhoto=`storage://${objectPath}`;photoUrls.set(editPhoto,URL.createObjectURL(file));$('#photo-data').value=editPhoto;setPhotoPreview(editPhoto);setSyncStatus('online','Synchronisiert');}catch(problem){setSyncStatus('error','Foto nicht hochgeladen');notice(problem.message||'Das Foto konnte nicht hochgeladen werden.');}finally{event.target.value='';}});
      $('#mobile-new').addEventListener('click',()=>{fillForm();showView('form');}); $('#mobile-form-save').addEventListener('click',()=>$('#vehicle-form').requestSubmit());
      $('#add-task').addEventListener('click',()=>{$('#task-form').reset();$('#task-form').elements.date.value=new Date().toISOString().slice(0,10);$('#task-modal').classList.add('open');}); $('#task-form').addEventListener('submit',event=>{event.preventDefault();const x=Object.fromEntries(new FormData(event.currentTarget));state.tasks.push({id:`task-${Date.now()}`,...x,done:false,updatedAt:new Date().toISOString()});saveState();renderTasks();$('#task-modal').classList.remove('open');notice('Aufgabe hinzugefügt.');}); document.addEventListener('change',event=>{if(event.target.matches('[data-task]')){const task=state.tasks.find(t=>t.id===event.target.dataset.task);task.done=event.target.checked;task.updatedAt=new Date().toISOString();saveState();renderTasks();}});
      function showAuth(message=''){ $('#access-error').textContent=message;$('#auth-screen').classList.remove('hidden');document.body.classList.add('locked'); }
      function setAuthError(message){ $('#access-error').textContent=message||'Der Zugang konnte nicht geöffnet werden.'; }
      function completeLogin(result){ workspaceId=result.workspaceId;currentUser=result.user;state=normaliseState(result.state);cacheState();$('#auth-screen').classList.add('hidden');document.body.classList.remove('locked');setSyncStatus('online','Synchronisiert');showView('home');startRealtime();hydratePhotoUrls(); }
      async function openWorkspaceForUser(user){ const {data:membership,error:memberError}=await client.from('av_workspace_members').select('workspace_id,display_name').eq('user_id',user.id).maybeSingle();if(memberError)throw memberError;if(!membership){showAuth('Bitte gib das gemeinsame Zugangs-Passwort ein.');return false;}const {data:workspace,error:workspaceError}=await client.from('av_workspaces').select('state').eq('id',membership.workspace_id).single();if(workspaceError)throw workspaceError;completeLogin({workspaceId:membership.workspace_id,user:{id:user.id,name:membership.display_name},state:workspace.state});return true; }
      async function ensureAnonymousSession(){ const {data:{session},error:sessionError}=await client.auth.getSession();if(sessionError)throw sessionError;if(session?.user?.is_anonymous)return session.user;if(session?.user)await client.auth.signOut();const {data,error}=await client.auth.signInAnonymously();if(error)throw error;if(!data.user)throw new Error('Es konnte keine anonyme Sitzung erstellt werden. Aktiviere in Supabase zuerst Anonymous Sign-Ins.');return data.user; }
      async function enterSharedWorkspace(password){ const user=await ensureAnonymousSession();const {data,error}=await client.rpc('av_enter_shared_workspace',{p_password:password});if(error)throw error;const record=Array.isArray(data)?data[0]:data;if(!record?.workspace_id||!record?.state)throw new Error('Der Zugangsdienst hat keine gültige Antwort geliefert.');completeLogin({workspaceId:record.workspace_id,user:{id:user.id,name:record.display_name||'Gemeinsamer Zugriff'},state:record.state}); }
      async function initializeApp(){ if(!client){setSyncStatus('error','Konfiguration fehlt');showAuth('Die Supabase-Konfiguration fehlt noch. Trage zuerst Projekt-URL und Publishable Key in config.js ein.');return;}setSyncStatus('','Verbinde …');try{const {data:{session},error}=await client.auth.getSession();if(error)throw error;if(session?.user?.is_anonymous&&await openWorkspaceForUser(session.user))return;showAuth();setSyncStatus('','Zugangs-Passwort erforderlich');}catch(error){setSyncStatus('error','Verbindung fehlgeschlagen');showAuth(error.message||'Supabase ist momentan nicht erreichbar.');} }
      $('#access-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('button[type="submit"]');const password=String(new FormData(form).get('password')||'');setAuthError('');submit.disabled=true;submit.textContent='Prüfe Zugang …';try{await enterSharedWorkspace(password);form.reset();}catch(problem){setAuthError(problem.message||'Das Zugangs-Passwort ist nicht richtig oder der Zugang ist noch nicht eingerichtet.');setSyncStatus('error','Zugang nicht geöffnet');}finally{submit.disabled=false;submit.textContent='Gemeinsamen Bestand öffnen';}});
      if(client)client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){workspaceId=null;currentUser=null;showAuth();setSyncStatus('','Zugangs-Passwort erforderlich');}});
      initializeApp();
      if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
